app = "producer-launchpad-app"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "npm run db:migrate:deploy"

[env]
  CHROME_PATH = "/usr/bin/chromium"
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
