name = "Producer Launchpad Web"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks"

[commands]
dev = "npm run dev:web"
build = "npm run build"

[auth]
path = "/auth"
callback_path = "/auth/callback"
